version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: revisao-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: revisaoBD
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - revisao-network

volumes:
  postgres-data:

networks:
  revisao-network:
    driver: bridge
